require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'lib/.rbnext/**/*'
    - 'lib/generators/**/templates/*.rb'
    - '.github/**/*'
    - templates/**/*
    - 'test/templates/**/*'
    - 'lib/ruby_bytes/thor.rb'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GlobalVars:
  Enabled: false
